version: 1.0.{build}
image:
- Visual Studio 2019
clone_folder: c:\retroplug
install:
  - cmd: appveyor DownloadFile https://github.com/Microsoft/vswhere/releases/download/2.3.2/vswhere.exe
  - cmd: appveyor DownloadFile https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-windows.zip
  - cmd: 7z e premake-5.0.0-alpha15-windows.zip
  - cmd: set PATH=c:\retroplug;%PATH%
build_script:
  - cmd: cd thirdparty
  - cmd: build.bat
  - cmd: cd SameBoy/retroplug
  - cmd: SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%"
  - cmd: bash -lc "pacman -S --needed --noconfirm pacman-mirrors"
  - cmd: bash -lc "pacman -S --needed --noconfirm git"
  - cmd: bash -lc "pacman -Syu --noconfirm"
  - cmd: bash -lc "pacman -S --needed --noconfirm mingw-w64-x86_64-toolchain autoconf automake libtool make patch mingw-w64-x86_64-libtool"
  - cmd: build.bat
  - cmd: cd ../../..
  - cmd: premake5 vs2019
  - cmd: msbuild build/vs2019/ScriptCompiler.vcxproj
  - cmd: premake5 vs2019
  - cmd: msbuild build/vs2019/RetroPlug-app.vcxproj
