version: 1.0.{build}
image:
- Visual Studio 2019
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
init:
  # Do a clean build if we are on the master branch (usually only for releases)
  - ps: IF ($env:APPVEYOR_REPO_BRANCH -eq "master") {$env:APPVEYOR_CACHE_SKIP_RESTORE = "true"}
clone_folder: c:\retroplug
cache: c:\retroplug\build
install:
  - cmd: appveyor DownloadFile https://github.com/Microsoft/vswhere/releases/download/2.3.2/vswhere.exe
  - cmd: appveyor DownloadFile https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-windows.zip
  - cmd: 7z e premake-5.0.0-alpha15-windows.zip
  - cmd: set PATH=c:\retroplug;%PATH%
build_script:
  - cmd: premake5 vs2019
  - cmd: msbuild build/vs2019/ScriptCompiler.vcxproj /property:Configuration=Release /property:Platform=x64
  - cmd: c:\retroplug\build\vs2019\bin\x64\Release\ScriptCompiler.exe c:\retroplug\src\compiler.config.lua
  - cmd: premake5 vs2019
  - cmd: msbuild build/vs2019/RetroPlug-app.vcxproj /property:Configuration=Release /property:Platform=x64
