name: CI
# Workflow file for windows
on:
  push:
    branches:
      - ci
  pull_request: {}

jobs:
  Windows:
    name: build-windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          submodules: recursive

    - name: Download premake
      uses: carlosperate/download-file-action@v1.0.3
      id: download-premake
      with:
          file-url: 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha16/premake-5.0.0-alpha16-windows.zip'

    - name: Download rgbds
      uses: carlosperate/download-file-action@v1.0.3
      id: download-rgbds
      with:
          file-url: 'https://github.com/gbdev/rgbds/releases/download/v0.5.1/rgbds-0.5.1-win64.zip'

    - name: Extract deps
      run: |
        cd ${{ github.workspace }}
        7z e premake-5.0.0-alpha16-windows.zip
        7z e rgbds-0.5.1-win64.zip

    - name: Running premake
      run: |
        cd ${{ github.workspace }}
        premake5.exe vs2019

    - name: Build script compiler
      run: |
        MSBuild.exe build/vs2019/ScriptCompiler.vcxproj /property:Configuration=Release /property:Platform=x64 /m
